# Uala challenge docker-compose file

services:
  mongo-database: 
    image: mongodb/mongodb-community-server
    container_name: local-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

  golang-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tweet-api
    ports:
      - "5000:5000"
    depends_on:
      - mongo-database
    
